#include "stylesheets.h"

StyleSec::StyleSec()
{

}


void StyleSec::getStyleSheet( QString& stylesheet, const QString& icons_theme, const int& theme_id )
{
    switch ( theme_id ) {
        case 1:
            StyleSec::styleAsh( stylesheet, icons_theme );
            break;
        case 2:
            break;
        case 3:
            break;
        case 4:
            break;
        default:
            break;
    }
}



void StyleSec::styleAsh( QString& ss , const QString& theme )
{
    ss= ""
        ////////////////
        //// SHARED ////
        "* {"
        "   color: rgb( 248, 248, 248 );"
        "}"
        // frames
        "QFrame,"
        "QWidget {"
        "   background-color: transparent;"
        "}"
        // tab widgets
        "QTabWidget {"
        "   selection-background-color: rgb( 32, 32, 32 );"
        "}"
        "QTabWidget::tab-bar {"
        "   alignment: left;"
        "}"
        "QTabBar {"
        "   background-color: transparent;"
        "}"
        "QTabBar::tab {"
        "   background-color: transparent;"
        "}"
        // tooltips
        "QToolTip {"
        "   border: 1px solid rgb( 144, 144, 144 );"
        "   background-color: rgb( 4, 4, 4 );"
        "}"
        // check boxes
        "QCheckBox::indicator {"
        "   width: 13px;"
        "   height : 13px;"
        "}"
        "QCheckBox::indicator:unchecked {"
        "   image: url(:/icons/icons/"+theme+"/checkbox_unchecked.png);"
        "}"
        "QCheckBox::indicator:indeterminate {"
        "   image: url(:/icons/icons/"+theme+"/checkbox_semichecked.png);"
        "}"
        "QCheckBox::indicator:checked {"
        "   image: url(:/icons/icons/"+theme+"/checkbox_checked.png);"
        "}"
        // radio buttons
        "QRadioButton::indicator {"
        "   width: 13px;"
        "   height : 13px;"
        "}"
        "QRadioButton::indicator:unchecked {"
        "   image: url(:/icons/icons/"+theme+"/radiobutton_unchecked.png);"
        "}"
        "QRadioButton::indicator:checked {"
        "   image: url(:/icons/icons/"+theme+"/radiobutton_checked.png);"
        "}"
        // line edits
        "QLineEdit {"
        "   color: rgb( 16, 16, 16 );"
        "   selection-color: rgb( 16, 16, 16 );"
        "   background-color: rgb( 216, 216, 216 );"
        "   selection-background-color: rgb( 192, 192, 192 );"
        "}"
        "QLineEdit::focus {"
        "   background-color: rgb( 248, 248, 248 );"
        "}"
        "QLineEdit:disabled {"
        "   background-color: rgb( 96, 96, 96 );"
        "}"
        // combo boxes
        "QComboBox {"
        "   background-color: rgb( 64, 64, 64 );"
        "   selection-background-color: rgb( 96, 96, 96 );"
        "}"
        "QComboBox::disabled {"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QComboBox QAbstractItemView {"
        "   border: 1px solid rgb( 128, 128, 128 );"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        // spin boxes
        "QSpinBox {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "   selection-background-color: rgb( 96, 96, 96 );"
        "}"
        "QSpinBox::focus {"
        "   border-color: rgb( 192, 192, 192 );"
        "}"
        "QSpinBox::disabled {"
        "   border-color: rgb( 48, 48, 48 );"
        "   color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 40, 40, 40 );"
        "}"
        "QSpinBox::up-button,"
        "QSpinBox::down-button {"
        "   padding: 2px;"
        "   border-left: 1px solid rgb( 192, 192, 192 );"
        "   background-color: rgb( 80, 80, 80 );"
        "}"
        "QSpinBox::up-button:hover,"
        "QSpinBox::down-button:hover {"
        "   background-color: rgb( 96, 96, 96 );"
        "}"
        "QSpinBox::up-button:off,"
        "QSpinBox::down-button:off {"
        "   background-color: rgb( 48, 48, 48 );"
        "}"
        "QSpinBox::up-button:disabled,"
        "QSpinBox::down-button:disabled {"
        "   border-left-color: rgb( 64, 64, 64 );"
        "   background-color: rgb( 40, 40, 40 );"
        "}"
        "QSpinBox::up-arrow {"
        "   width: 7px;"
        "   height: 7px;"
        "   padding: 2px;"
        "   image: url(:/icons/icons/"+theme+"/spinbox_add.png);"
        "}"
        "QSpinBox::up-arrow:off,"
        "QSpinBox::up-arrow:disabled {"
        "   image: url(:/icons/icons/midtone/spinbox_add.png);"
        "}"
        "QSpinBox::down-arrow {"
        "   width: 8px;"
        "   height: 8px;"
        "   image: url(:/icons/icons/"+theme+"/spinbox_sub.png);"
        "}"
        "QSpinBox::down-arrow:off,"
        "QSpinBox::down-arrow:disabled {"
        "   image: url(:/icons/icons/midtone/spinbox_sub.png);"
        "}"
        // scroll bars
        "QScrollBar:horizontal {"
        "   height: 12px;"
        "   background-color: rgb( 96, 96, 96 );"
        "}"
        "QScrollBar::handle:horizontal {"
        "   min-width: 16px;"
        "   margin: 5px 12px 5px 12px;"
        "   background-color: rgb( 192, 192, 192 );"
        "}"
        "QScrollBar::handle:horizontal:hover {"
        "   margin: 4px 12px 4px 12px;"
        "}"
        "QScrollBar:vertical {"
        "   width: 12px;"
        "   background-color: rgb( 96, 96, 96 );"
        "}"
        "QScrollBar::handle:vertical {"
        "   min-height: 16px;"
        "   margin: 12px 5px 12px 5px;"
        "   background-color: rgb( 192, 192, 192 );"
        "}"
        "QScrollBar::handle:vertical:hover {"
        "   margin:12px 4px 12px 4px;"
        "}"
        // slider
        "QSlider::groove:horizontal {"
        "   height: 2px;"
        "   border: 1px solid rgb( 144, 144, 144 );"
        "   background-color: rgb( 128, 128, 128 );"
        "}"
        "QSlider::add-page:horizontal {"
        "   border: 0px;"
        "   background-color: rgb( 82, 82, 82 );"
        "}"
        "QSlider::sub-page:horizontal {"
        "   border: 1px solid rgb( 144, 144, 144 );"
        "   background-color: rgb( 128, 128, 128 );"
        "}"
        "QSlider::handle:horizontal {"
        "   width: 12px;"
        "   margin: -5px 0px;"
        "   border: 1px solid rgb( 192, 192, 192 );"
        "   border-radius: 4px;"
        "   background-color: rgb( 48, 48, 48 );"
        "}"
        "QSlider::handle:hover:horizontal {"
        "   border: 1px solid rgb( 248, 248, 248 );"
        "}"
        // charts
        "QGraphicsView {"
        "   border-radius: 4px;"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        // tables, trees and headers
        "QTreeWidget,"
        "QTableWidget {"
        "   background-color: rgb( 32, 32, 32 );"
        "   selection-color: rgb( 248, 248, 248 );"
        "   selection-background-color: rgb( 64, 64, 64 );"
        "}"
        "QTreeWidget QScrollBar::handle:vertical,"
        "QTableWidget QScrollBar::handle:vertical {"
        "   padding: 12px;"
        "}"
        "QHeaderView {"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        // text browser
        "QTextBrowser {"
        "   color: rgb( 192, 192, 192 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   selection-color: rgb( 248, 248, 248 );"
        "   selection-background-color: rgb( 64, 64, 64 );"
        "}"
        "QTextBrowser QScrollBar::handle:vertical {"
        "   padding: 12px;"
        "}"
        //////////////
        //// MENU ////
        "QMenuBar {"
        "   color: rgb( 144, 144, 144 );"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QMenuBar::item:selected {"
        "   color: rgb( 144, 144, 144 );"
        "   background-color: rgb( 64, 64, 64 );"
        "   border-radius: 4px;"
        "}"
        "QMenuBar::item:pressed {"
        "   color: rgb( 32, 32, 32 );"
        "   background-color: rgb( 144, 144, 144 );"
        "   border-radius: 0px;"
        "   border-top-left-radius: 4px;"
        "   border-top-right-radius: 4px;"
        "}"
        // menu dropdown
        "QMenu {"
        "   color: rgb( 32, 32, 32 );"
        "   background-color: rgb( 144, 144, 144 );"
        "}"
        "QMenu::item:selected {"
        "   background-color: rgb( 192, 192, 192 );"
        "}"
        //////////////
        //// MAIN ////
        // window
        "QWidget#mainwidget {"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        // tabs buttons
        "QFrame#frame_Tabs_Buttons {"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QPushButton#button_Tab_Log,"
        "QPushButton#button_Tab_View,"
        "QPushButton#button_Tab_Conf {"
        "   border-top-left-radius: 8px;"
        "   border-bottom-left-radius: 8px;"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        "QPushButton#button_Tab_Log::flat,"
        "QPushButton#button_Tab_View::flat,"
        "QPushButton#button_Tab_Conf::flat {"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QPushButton#button_Tab_Log::flat:hover,"
        "QPushButton#button_Tab_View::flat:hover,"
        "QPushButton#button_Tab_Conf::flat:hover {"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        // tabs pages
        "QStackedWidget#stacked_Tabs_Pages {"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        //////////////
        //// LOGS ////
        // switcher buttons
        "QFrame#frame_Logs_Down {"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        "QPushButton#button_Logs_Down:hover {"
        "   border-radius: 16px;"
        "   background-color: rgb( 24, 24, 24 );"
        "   icon: url(:/icons/icons/"+theme+"/down.png);"
        "}"
        "QFrame#frame_Logs_Up {"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        "QPushButton#button_Logs_Up::flat:hover {"
        "   border-radius: 16px;"
        "   background-color: rgb( 24, 24, 24 );"
        "   icon: url(:/icons/icons/"+theme+"/up.png);"
        "}"
        // web servers buttons
        "QPushButton#button_LogFiles_Apache,"
        "QPushButton#button_LogFiles_Nginx,"
        "QPushButton#button_LogFiles_Iis {"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_LogFiles_Apache::flat,"
        "QPushButton#button_LogFiles_Nginx::flat,"
        "QPushButton#button_LogFiles_Iis::flat {"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "   color: rgb( 144, 144, 144 );"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        "QPushButton#button_LogFiles_Apache::flat:hover,"
        "QPushButton#button_LogFiles_Nginx::flat:hover,"
        "QPushButton#button_LogFiles_Iis::flat:hover {"
        "   border: 1px solid rgb( 128, 128, 128 );"
        "   color: rgb( 248, 248, 248 );"
        "}"
        "QPushButton#button_LogFiles_Apache::disabled,"
        "QPushButton#button_LogFiles_Nginx::disabled,"
        "QPushButton#button_LogFiles_Iis::disabled {"
        "   color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        // logs list
        "QTreeWidget#listLogFiles::indicator {"
        "   width: 13px;"
        "   height: 13px;"
        "   margin-left: -4px;"
        "   margin-right: 4px;"
        "}"
        "QTreeWidget#listLogFiles::indicator:unchecked {"
        "   image: url(:/icons/icons/"+theme+"/checkbox_unchecked.png);"
        "}"
        "QTreeWidget#listLogFiles::indicator:checked {"
        "   image: url(:/icons/icons/"+theme+"/checkbox_checked.png);"
        "}"
        // view file button
        "QPushButton#button_LogFiles_ViewFile {"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_LogFiles_ViewFile:hover {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "}"
        "QPushButton#button_LogFiles_ViewFile::disabled {"
        "   background-color: rgb( 40, 40, 40 );"
        "}"
        // refresh button
        "QPushButton#button_LogFiles_RefreshList {"
        "   border: 1px solid rgb( 32, 32, 32 );"
        "   border-radius: 16px;"
        "   background-color: transparent;"
        "}"
        "QPushButton#button_LogFiles_RefreshList:hover {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "}"
        // parse logs button
        "QPushButton#button_MakeStats_Start {"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_MakeStats_Start:hover {"
        "   background-color: rgb( 82, 82, 82 );"
        "}"
        "QPushButton#button_MakeStats_Start::disabled {"
        "   color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        ///////////////
        //// STATS ////
        // statistics tabs buttons
        "QFrame#frame_Stats_Buttons {"
        "   border: 2px solid rgb( 32, 32, 32 );"
        "   border-bottom-left-radius: 4px;"
        "   border-bottom-right-radius: 4px;"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        "QPushButton#button_Tab_StatsWarn,"
        "QPushButton#button_Tab_StatsSpeed,"
        "QPushButton#button_Tab_StatsCount,"
        "QPushButton#button_Tab_StatsDay,"
        "QPushButton#button_Tab_StatsRelat,"
        "QPushButton#button_Tab_StatsGlob {"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_Tab_StatsWarn::flat,"
        "QPushButton#button_Tab_StatsSpeed::flat,"
        "QPushButton#button_Tab_StatsCount::flat,"
        "QPushButton#button_Tab_StatsDay::flat,"
        "QPushButton#button_Tab_StatsRelat::flat,"
        "QPushButton#button_Tab_StatsGlob::flat {"
        "   background-color: transparent;"
        "}"
        "QPushButton#button_Tab_StatsWarn::flat:hover,"
        "QPushButton#button_Tab_StatsSpeed::flat:hover,"
        "QPushButton#button_Tab_StatsCount::flat:hover,"
        "QPushButton#button_Tab_StatsDay::flat:hover,"
        "QPushButton#button_Tab_StatsRelat::flat:hover,"
        "QPushButton#button_Tab_StatsGlob::flat:hover {"
        "   border: 1px solid rgb( 48, 48, 48 );"
        "   background-color: rgb( 24, 24, 24 );"
        "}"
        // draw buttons
        "QPushButton#button_StatsWarn_Update,"
        "QPushButton#button_StatsWarn_Draw,"
        "QPushButton#button_StatsSpeed_Draw,"
        "QPushButton#button_StatsCount_Draw,"
        "QPushButton#button_StatsDay_Draw,"
        "QPushButton#button_StatsRelat_Draw,"
        "QPushButton#button_StatsGlob_Draw {"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_StatsWarn_Update:hover,"
        "QPushButton#button_StatsWarn_Draw:hover,"
        "QPushButton#button_StatsSpeed_Draw:hover,"
        "QPushButton#button_StatsCount_Draw:hover,"
        "QPushButton#button_StatsDay_Draw:hover,"
        "QPushButton#button_StatsRelat_Draw:hover,"
        "QPushButton#button_StatsGlob_Draw:hover {"
        "   border: 1px solid rgb( 128, 128, 128 );"
        "   background-color: rgb( 82, 82, 82 );"
        "}"
        "QPushButton#button_StatsWarn_Update::disabled {"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   icon: url(:/icons/icons/midtone/save.png);"
        "}"
        // stats warn
        "QTableWidget#table_StatsWarn::indicator {"
        "   width: 13px;"
        "   height: 13px;"
        "}"
        "QTableWidget#table_StatsWarn::indicator:unchecked {"
        "   image: url(:/icons/icons/"+theme+"/checkbox_unchecked.png);"
        "}"
        "QTableWidget#table_StatsWarn::indicator:checked {"
        "   image: url(:/icons/icons/"+theme+"/checkbox_checked.png);"
        "}"
        "QTableWidget#table_StatsWarn QScrollBar::handle:vertical {"
        "   padding: 12px;"
        "}"
        // stats count
        "QScrollArea#scrollArea_StatsCount {"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        "QWidget#scrollAreaContent_StatsCount {"
        "   background-color: transparent;"
        "}"
        "QPushButton#button_StatsCount_Protocol,"
        "QPushButton#button_StatsCount_Method,"
        "QPushButton#button_StatsCount_Uri,"
        "QPushButton#button_StatsCount_Query,"
        "QPushButton#button_StatsCount_Response,"
        "QPushButton#button_StatsCount_Referrer,"
        "QPushButton#button_StatsCount_Cookie,"
        "QPushButton#button_StatsCount_UserAgent,"
        "QPushButton#button_StatsCount_Client {"
        "   border-radius: 4px;"
        "   background-color: rgb( 96, 96, 96 );"
        "}"
        "QPushButton#button_StatsCount_Protocol::flat,"
        "QPushButton#button_StatsCount_Method::flat,"
        "QPushButton#button_StatsCount_Uri::flat,"
        "QPushButton#button_StatsCount_Query::flat,"
        "QPushButton#button_StatsCount_Response::flat,"
        "QPushButton#button_StatsCount_Referrer::flat,"
        "QPushButton#button_StatsCount_Cookie::flat,"
        "QPushButton#button_StatsCount_UserAgent::flat,"
        "QPushButton#button_StatsCount_Client::flat {"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QPushButton#button_StatsCount_Protocol::flat:hover,"
        "QPushButton#button_StatsCount_Method::flat:hover,"
        "QPushButton#button_StatsCount_Uri::flat:hover,"
        "QPushButton#button_StatsCount_Query::flat:hover,"
        "QPushButton#button_StatsCount_Response::flat:hover,"
        "QPushButton#button_StatsCount_Referrer::flat:hover,"
        "QPushButton#button_StatsCount_Cookie::flat:hover,"
        "QPushButton#button_StatsCount_UserAgent::flat:hover,"
        "QPushButton#button_StatsCount_Client::flat:hover {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        // stats globals
        "QFrame#frame_StatsGlob_WebServers {"
        "   border-radius: 4px;"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_StatsGlob_Apache,"
        "QPushButton#button_StatsGlob_Nginx,"
        "QPushButton#button_StatsGlob_Iis {"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_StatsGlob_Apache::flat,"
        "QPushButton#button_StatsGlob_Nginx::flat,"
        "QPushButton#button_StatsGlob_Iis::flat {"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "   color: rgb( 144, 144, 144 );"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        "QPushButton#button_StatsGlob_Apache::flat:hover,"
        "QPushButton#button_StatsGlob_Nginx::flat:hover,"
        "QPushButton#button_StatsGlob_Iis::flat:hover {"
        "   border: 1px solid rgb( 128, 128, 128 );"
        "   color: rgb( 248, 248, 248 );"
        "}"
        "QPushButton#button_StatsGlob_Apache::disabled,"
        "QPushButton#button_StatsGlob_Nginx::disabled,"
        "QPushButton#button_StatsGlob_Iis::disabled {"
        "   color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QScrollArea#scrollArea_StatsGlob_Recur,"
        "QScrollArea#scrollArea_StatsGlob_Perf,"
        "QScrollArea#scrollArea_StatsGlob_Traffic,"
        "QScrollArea#scrollArea_StatsGlob_Work {"
        "   border: 1px solid rgb( 128, 128, 128 );"
        "   background-color: rgb( 16, 16, 16 );"
        "}"
        // styled frames
        "QFrame#frame_StatsWarn_Logs,"
        "QFrame#frame_StatsDay_Date,"
        "QFrame#frame_StatsRelat_Field {"
        "   border: 1px solid rgb( 128, 128, 128 );"
        "}"
        // lines separators
        "QFrame#gline_StatsWarn_1,"
        "QFrame#gline_StatsWarn_2,"
        "QFrame#gline_StatsWarn_3,"
        "QFrame#gline_StatsDay_1,"
        "QFrame#gline_StatsDay_2,"
        "QFrame#gline_StatsRelat_1,"
        "QFrame#gline_StatsGlob_Recur_1,"
        "QFrame#gline_StatsGlob_Recur_2,"
        "QFrame#gline_StatsGlob_Recur_3,"
        "QFrame#gline_StatsGlob_Perf_1,"
        "QFrame#gline_StatsGlob_Perf_2,"
        "QFrame#gline_StatsGlob_Traffic_1,"
        "QFrame#gline_StatsGlob_Traffic_2,"
        "QFrame#gline_StatsGlob_Work_1,"
        "QFrame#gline_StatsGlob_Work_2 {"
        "   border: 1px solid rgb( 16, 16, 16 );"
        "   background-color: rgb( 192, 192, 192 );"
        "}"
        "QFrame#gline_StatsSpeed_1,"
        "QFrame#gline_StatsCount_1 {"
        "   border: 1px solid rgb( 16, 16, 16 );"
        "   margin: 2px 0px 3px 0px;"
        "   background-color: rgb( 192, 192, 192 );"
        "}"
        /////////////////
        //// CONFIGS ////
        // outer tabs
        "QTabWidget#ConfTabs QTabBar::tab {"
        "   margin-top: 3px;"
        "   margin-bottom: 1px;"
        "   padding: 8px 6px;"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-left: 4px solid rgb( 96, 96, 96 );"
        "   border-right: 0px;"
        "   border-top-left-radius: 4px;"
        "   border-bottom-left-radius: 4px;"
        "}"
        "QTabWidget#ConfTabs QTabBar::tab:selected {"
        "   color: rgb( 248, 248, 248 );"
        "}"
        "QTabWidget#ConfTabs QTabBar::tab:!selected {"
        "   border-color: rgb( 48, 48, 48 );"
        "   border-left: 1px solid rgb( 48, 48, 48 );"
        "   color: rgb( 128, 128, 128 );"
        "}"
        "QTabWidget#ConfTabs QTabBar::tab:!selected:hover {"
        "   border-color: rgb( 96, 96, 96 );"
        "   color: rgb( 192, 192, 192 );"
        "}"
        // inner tabs
        "QTabWidget#tabs_ConfGeneral QTabBar::tab,"
        "QTabWidget#tabs_ConfLogs QTabBar::tab {"
        "   margin: 0px;"
        "   margin-right: 4px;"
        "   padding: 6px 8px;"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-bottom: 0px;"
        "   border-top-left-radius: 4px;"
        "   border-bottom-left-radius: 0px;"
        "   border-top-right-radius: 4px;"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QTabWidget#tabs_ConfGeneral QTabBar::tab:!selected,"
        "QTabWidget#tabs_ConfLogs QTabBar::tab:!selected {"
        "   background-color: rgb( 24, 24, 24 );"
        "}"
        "QTabWidget#tabs_ConfGeneral::pane,"
        "QTabWidget#tabs_ConfLogs::pane {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-top-right-radius: 4px;"
        "   border-bottom-left-radius: 4px;"
        "   border-bottom-right-radius: 4px;"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        // sub tabs
        "QTabWidget#tabs_ConfApache QTabBar,"
        "QTabWidget#tabs_ConfNginx QTabBar,"
        "QTabWidget#tabs_ConfIis QTabBar {"
        "   border: 0px;"
        "}"
        "QTabWidget#tabs_ConfApache QTabBar::tab,"
        "QTabWidget#tabs_ConfNginx QTabBar::tab,"
        "QTabWidget#tabs_ConfIis QTabBar::tab {"
        "   background-color: rgb( 48, 48, 48 );"
        "}"
        "QTabWidget#tabs_ConfApache QTabBar::tab:!selected,"
        "QTabWidget#tabs_ConfNginx QTabBar::tab:!selected,"
        "QTabWidget#tabs_ConfIis QTabBar::tab:!selected {"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "   background-color: rgb( 40, 40, 40 );"
        "}"
        "QTabWidget#tabs_ConfApache::pane,"
        "QTabWidget#tabs_ConfNginx::pane,"
        "QTabWidget#tabs_ConfIis::pane {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   background-color: rgb( 48, 48, 48 );"
        "}"
        // panes
        "QWidget#confGeneral,"
        "QWidget#confLogs {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-top-right-radius: 4px;"
        "   border-bottom-left-radius: 4px;"
        "   border-bottom-right-radius: 4px;"
        "   background-color: transparent;"
        "}"
        "QWidget#tab_confWindow,"
        "QWidget#tab_confTextBrowser,"
        "QWidget#tab_confCharts,"
        "QWidget#tab_confDatabases,"
        "QWidget#tab_confLogs_Default,"
        "QWidget#tab_confLogs_Control,"
        "QWidget#tab_confLogs_Apache,"
        "QWidget#tab_confLogs_Nginx,"
        "QWidget#tab_confLogs_Iis {"
        "   border: 0px;"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        "QWidget#tab_confApache_Paths,"
        "QWidget#tab_confApache_Formats,"
        "QWidget#tab_confApache_Warnlists,"
        "QWidget#tab_confApache_Blacklists,"
        "QWidget#tab_confNginx_Paths,"
        "QWidget#tab_confNginx_Formats,"
        "QWidget#tab_confNginx_Warnlists,"
        "QWidget#tab_confNginx_Blacklists,"
        "QWidget#tab_confIis_Paths,"
        "QWidget#tab_confIis_Formats,"
        "QWidget#tab_confIis_Warnlists,"
        "QWidget#tab_confIis_Blacklists {"
        "   background-color: rgb( 48, 48, 48 );"
        "}"
        // line separators
        "QFrame#gline_ConfTextBrowser {"
        "   border: 2px solid rgb( 32, 32, 32 );"
        "   margin: 13px 0px 14px 0px;"
        "   background-color: rgb( 192, 192, 192 );"
        "}"
        // save buttons
        "QPushButton#button_ConfDatabases_Data_Save,"
        "QPushButton#button_ConfDatabases_Hashes_Save,"
        "QPushButton#button_ConfApache_Path_Save,"
        "QPushButton#button_ConfApache_Format_Save,"
        "QPushButton#button_ConfNginx_Path_Save,"
        "QPushButton#button_ConfNginx_Format_Save,"
        "QPushButton#button_ConfIis_Path_Save,"
        "QPushButton#button_ConfIis_Format_Save {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_ConfDatabases_Data_Save:hover,"
        "QPushButton#button_ConfDatabases_Hashes_Save:hover,"
        "QPushButton#button_ConfApache_Path_Save:hover,"
        "QPushButton#button_ConfApache_Format_Save:hover,"
        "QPushButton#button_ConfNginx_Path_Save:hover,"
        "QPushButton#button_ConfNginx_Format_Save:hover,"
        "QPushButton#button_ConfIis_Path_Save:hover,"
        "QPushButton#button_ConfIis_Format_Save:hover {"
        "   border-color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 82, 82, 82 );"
        "}"
        "QPushButton#button_ConfDatabases_Data_Save::disabled,"
        "QPushButton#button_ConfDatabases_Hashes_Save::disabled,"
        "QPushButton#button_ConfApache_Path_Save::disabled,"
        "QPushButton#button_ConfApache_Path_Save::disabled,"
        "QPushButton#button_ConfNginx_Path_Save::disabled,"
        "QPushButton#button_ConfNginx_Format_Save::disabled,"
        "QPushButton#button_ConfIis_Path_Save::disabled,"
        "QPushButton#button_ConfIis_Format_Save::disabled {"
        "   border-color: rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   icon: url(:/icons/icons/midtone/save.png);"
        "}"
        // sample buttons
        "QPushButton#button_ConfApache_Format_Sample,"
        "QPushButton#button_ConfNginx_Format_Sample,"
        "QPushButton#button_ConfIis_Format_Sample {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_ConfApache_Format_Sample:hover,"
        "QPushButton#button_ConfNginx_Format_Sample:hover,"
        "QPushButton#button_ConfIis_Format_Sample:hover {"
        "   border-color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 82, 82, 82 );"
        "}"
        // sample previews
        "QWidget#scrollAreaContent_ConfApache_Format_Sample,"
        "QWidget#scrollAreaContent_ConfNginx_Format_Sample,"
        "QWidget#scrollAreaContent_ConfIis_Format_Sample {"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "}"
        // help buttons
        "QPushButton#button_ConfApache_Format_Help,"
        "QPushButton#button_ConfNginx_Format_Help,"
        "QPushButton#button_ConfIis_Format_Help {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_ConfApache_Format_Help:hover,"
        "QPushButton#button_ConfNginx_Format_Help:hover,"
        "QPushButton#button_ConfIis_Format_Help:hover {"
        "   border-color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 82, 82, 82 );"
        "}"
        // warnlists / blacklists
        "QListWidget#list_ConfApache_Warnlist_List,"
        "QListWidget#list_ConfApache_Blacklist_List,"
        "QListWidget#list_ConfNginx_Warnlist_List,"
        "QListWidget#list_ConfNginx_Blacklist_List,"
        "QListWidget#list_ConfIis_Warnlist_List,"
        "QListWidget#list_ConfIis_Blacklist_List {"
        "   padding: 4px;"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   selection-background-color: rgb( 64, 64, 64 );"
        "}"
        "QListWidget#list_ConfApache_Warnlist_List::disabled,"
        "QListWidget#list_ConfApache_Blacklist_List::disabled,"
        "QListWidget#list_ConfNginx_Warnlist_List::disabled,"
        "QListWidget#list_ConfNginx_Blacklist_List::disabled,"
        "QListWidget#list_ConfIis_Warnlist_List::disabled,"
        "QListWidget#list_ConfIis_Blacklist_List::disabled {"
        "   border: 1px solid rgb( 64, 64, 64 );"
        "   color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 40, 40, 40 );"
        "}"
        "QListWidget#list_ConfApache_Warnlist_List::item,"
        "QListWidget#list_ConfApache_Blacklist_List::item,"
        "QListWidget#list_ConfNginx_Warnlist_List::item,"
        "QListWidget#list_ConfNginx_Blacklist_List::item,"
        "QListWidget#list_ConfIis_Warnlist_List::item,"
        "QListWidget#list_ConfIis_Blacklist_List::item {"
        "   padding: 4px;"
        "}"
        // lists buttons
        "QPushButton#button_ConfApache_Warnlist_Add,"
        "QPushButton#button_ConfApache_Warnlist_Remove,"
        "QPushButton#button_ConfApache_Warnlist_Up,"
        "QPushButton#button_ConfApache_Warnlist_Down,"
        "QPushButton#button_ConfApache_Blacklist_Add,"
        "QPushButton#button_ConfApache_Blacklist_Remove,"
        "QPushButton#button_ConfApache_Blacklist_Up,"
        "QPushButton#button_ConfApache_Blacklist_Down,"
        "QPushButton#button_ConfNginx_Warnlist_Add,"
        "QPushButton#button_ConfNginx_Warnlist_Remove,"
        "QPushButton#button_ConfNginx_Warnlist_Up,"
        "QPushButton#button_ConfNginx_Warnlist_Down,"
        "QPushButton#button_ConfNginx_Blacklist_Add,"
        "QPushButton#button_ConfNginx_Blacklist_Remove,"
        "QPushButton#button_ConfNginx_Blacklist_Up,"
        "QPushButton#button_ConfNginx_Blacklist_Down,"
        "QPushButton#button_ConfIis_Warnlist_Add,"
        "QPushButton#button_ConfIis_Warnlist_Remove,"
        "QPushButton#button_ConfIis_Warnlist_Up,"
        "QPushButton#button_ConfIis_Warnlist_Down,"
        "QPushButton#button_ConfIis_Blacklist_Add,"
        "QPushButton#button_ConfIis_Blacklist_Remove,"
        "QPushButton#button_ConfIis_Blacklist_Up,"
        "QPushButton#button_ConfIis_Blacklist_Down {"
        "   border: 1px solid rgb( 96, 96, 96 );"
        "   border-radius: 4px;"
        "   background-color: rgb( 64, 64, 64 );"
        "}"
        "QPushButton#button_ConfApache_Warnlist_Add:hover,"
        "QPushButton#button_ConfApache_Warnlist_Remove:hover,"
        "QPushButton#button_ConfApache_Warnlist_Up:hover,"
        "QPushButton#button_ConfApache_Warnlist_Down:hover,"
        "QPushButton#button_ConfApache_Blacklist_Add:hover,"
        "QPushButton#button_ConfApache_Blacklist_Remove:hover,"
        "QPushButton#button_ConfApache_Blacklist_Up:hover,"
        "QPushButton#button_ConfApache_Blacklist_Down:hover,"
        "QPushButton#button_ConfNginx_Warnlist_Add:hover,"
        "QPushButton#button_ConfNginx_Warnlist_Remove:hover,"
        "QPushButton#button_ConfNginx_Warnlist_Up:hover,"
        "QPushButton#button_ConfNginx_Warnlist_Down:hover,"
        "QPushButton#button_ConfNginx_Blacklist_Add:hover,"
        "QPushButton#button_ConfNginx_Blacklist_Remove:hover,"
        "QPushButton#button_ConfNginx_Blacklist_Up:hover,"
        "QPushButton#button_ConfNginx_Blacklist_Down:hover,"
        "QPushButton#button_ConfIis_Warnlist_Add:hover,"
        "QPushButton#button_ConfIis_Warnlist_Remove:hover,"
        "QPushButton#button_ConfIis_Warnlist_Up:hover,"
        "QPushButton#button_ConfIis_Warnlist_Down:hover,"
        "QPushButton#button_ConfIis_Blacklist_Add:hover,"
        "QPushButton#button_ConfIis_Blacklist_Remove:hover,"
        "QPushButton#button_ConfIis_Blacklist_Up:hover,"
        "QPushButton#button_ConfIis_Blacklist_Down:hover {"
        "   border-color: rgb( 128, 128, 128 );"
        "   background-color: rgb( 82, 82, 82 );"
        "}"
        "QPushButton#button_ConfApache_Warnlist_Add::disabled,"
        "QPushButton#button_ConfApache_Blacklist_Add::disabled,"
        "QPushButton#button_ConfNginx_Warnlist_Add::disabled,"
        "QPushButton#button_ConfNginx_Blacklist_Add::disabled,"
        "QPushButton#button_ConfIis_Warnlist_Add::disabled,"
        "QPushButton#button_ConfIis_Blacklist_Add::disabled {"
        "   border-color: rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   icon: url(:/icons/icons/add.png), #fff;"
        "}"
        "QPushButton#button_ConfApache_Warnlist_Remove::disabled,"
        "QPushButton#button_ConfApache_Blacklist_Remove::disabled,"
        "QPushButton#button_ConfNginx_Warnlist_Remove::disabled,"
        "QPushButton#button_ConfNginx_Blacklist_Remove::disabled,"
        "QPushButton#button_ConfIis_Warnlist_Remove::disabled,"
        "QPushButton#button_ConfIis_Blacklist_Remove::disabled {"
        "   border-color: rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   icon: url(:/icons/icons/rem.png), #fff;"
        "}"
        "QPushButton#button_ConfApache_Warnlist_Up::disabled,"
        "QPushButton#button_ConfApache_Blacklist_Up::disabled,"
        "QPushButton#button_ConfNginx_Warnlist_Up::disabled,"
        "QPushButton#button_ConfNginx_Blacklist_Up::disabled,"
        "QPushButton#button_ConfIis_Warnlist_Up::disabled,"
        "QPushButton#button_ConfIis_Blacklist_Up::disabled {"
        "   border-color: rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   icon: url(:/icons/icons/up.png), #fff;"
        "}"
        "QPushButton#button_ConfApache_Warnlist_Down::disabled,"
        "QPushButton#button_ConfApache_Blacklist_Down::disabled,"
        "QPushButton#button_ConfNginx_Warnlist_Down::disabled,"
        "QPushButton#button_ConfNginx_Blacklist_Down::disabled,"
        "QPushButton#button_ConfIis_Warnlist_Down::disabled,"
        "QPushButton#button_ConfIis_Blacklist_Down::disabled {"
        "   border-color: rgb( 64, 64, 64 );"
        "   background-color: rgb( 32, 32, 32 );"
        "   icon: url(:/icons/icons/down.png), #fff;"
        "}"
        "";
}


void StyleSec::styleCandy( QString& ss, const QString& theme )
{

}


void StyleSec::styleHerb( QString& ss, const QString& theme )
{

}


void StyleSec::stylePowder( QString& ss, const QString& theme )
{

}
